// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"time"

	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OpenIdConnectScopes = "openIdConnect.Scopes"
)

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Service   *string    `json:"service,omitempty"`
	Status    *string    `json:"status,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Version   *string    `json:"version,omitempty"`
}

// Workflow defines model for Workflow.
type Workflow struct {
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        *string             `json:"name,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Status check
	// (GET /status)
	GetStatus(ctx echo.Context) error
	// Delete a workflow
	// (DELETE /workflows)
	DeleteWorkflow(ctx echo.Context) error
	// List workflows
	// (GET /workflows)
	ListWorkflows(ctx echo.Context) error
	// Partially update a workflow
	// (PATCH /workflows)
	PatchWorkflow(ctx echo.Context) error
	// Create or update a workflow
	// (PUT /workflows)
	PutWorkflow(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatus(ctx echo.Context) error {
	var err error

	ctx.Set(OpenIdConnectScopes, []string{"openid", "profile", "email"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStatus(ctx)
	return err
}

// DeleteWorkflow converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteWorkflow(ctx echo.Context) error {
	var err error

	ctx.Set(OpenIdConnectScopes, []string{"evolve:read", "evolve:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteWorkflow(ctx)
	return err
}

// ListWorkflows converts echo context to params.
func (w *ServerInterfaceWrapper) ListWorkflows(ctx echo.Context) error {
	var err error

	ctx.Set(OpenIdConnectScopes, []string{"evolve:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListWorkflows(ctx)
	return err
}

// PatchWorkflow converts echo context to params.
func (w *ServerInterfaceWrapper) PatchWorkflow(ctx echo.Context) error {
	var err error

	ctx.Set(OpenIdConnectScopes, []string{"evolve:read", "evolve:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchWorkflow(ctx)
	return err
}

// PutWorkflow converts echo context to params.
func (w *ServerInterfaceWrapper) PutWorkflow(ctx echo.Context) error {
	var err error

	ctx.Set(OpenIdConnectScopes, []string{"evolve:read", "evolve:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutWorkflow(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.GET(baseURL+"/status", wrapper.GetStatus)
	router.DELETE(baseURL+"/workflows", wrapper.DeleteWorkflow)
	router.GET(baseURL+"/workflows", wrapper.ListWorkflows)
	router.PATCH(baseURL+"/workflows", wrapper.PatchWorkflow)
	router.PUT(baseURL+"/workflows", wrapper.PutWorkflow)

}
