package main

import (
	"fmt"
	"os"
	"text/template"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "setup",
	Short: "Setup utility for Evolutionary MCP",
	Long:  `A utility to help configure the Evolutionary MCP environment.`,
}

var envCmd = &cobra.Command{
	Use:   "env",
	Short: "Generate a .env file with default values and instructions",
	Run: func(cmd *cobra.Command, args []string) {
		createEnvFile()
	},
}

func init() {
	rootCmd.AddCommand(envCmd)
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

// EnvGroup groups related environment variables
type EnvGroup struct {
	Name string
	Vars []EnvVar
}

// EnvVar represents a single environment variable definition
type EnvVar struct {
	Key     string
	Value   string
	Comment string
}

func createEnvFile() {
	// Define the source of truth for .env generation here.
	// Keep this in sync with backend/internal/config/config.go
	groups := []EnvGroup{
		{
			Name: "Database Configuration",
			Vars: []EnvVar{
				{"DB_HOST", "localhost", "Database host"},
				{"DB_PORT", "5432", "Database port"},
				{"DB_USER", "user", "Database user"},
				{"DB_PASSWORD", "password", "Database password"},
				{"DB_NAME", "db", "Database name"},
				{"DB_SSLMODE", "disable", "SSL mode (disable, require, verify-full)"},
			},
		},
		{
			Name: "ML Sidecar Configuration",
			Vars: []EnvVar{
				{"ML_SIDECAR_URL", "http://localhost:8001", "URL for the Python ML service"},
			},
		},
		{
			Name: "Authentication (Okta)",
			Vars: []EnvVar{
				{"AUTH_OKTA_DOMAIN", "https://{yourOktaDomain}", "Your Okta Domain (e.g., https://dev-123456.okta.com/oauth2/default)"},
				{"AUTH_CLIENT_ID", "{backendClientId}", "Backend Web App Client ID"},
				{"AUTH_CLIENT_SECRET", "{backendClientSecret}", "Backend Web App Client Secret"},
				{"AUTH_SWAGGER_CLIENT_ID", "{spaClientId}", "Frontend/Swagger SPA Client ID (PKCE)"},
				{"AUTH_REDIRECT_URL", "http://localhost:8080/auth/callback", "Redirect URL for the backend callback"},
			},
		},
		{
			Name: "TLS Configuration",
			Vars: []EnvVar{
				{"TLS_ENABLE", "false", "Set to true to enable HTTPS"},
				{"TLS_CERT_FILE", "", "Path to certificate file"},
				{"TLS_KEY_FILE", "", "Path to key file"},
				{"TLS_HOSTNAMES", "localhost,127.0.0.1", "Hostnames for self-signed cert generation (comma separated)"},
			},
		},
	}

	tmpl := `# Evolutionary MCP Environment Configuration
# Generated by setup utility
{{- range .}}

# {{.Name}}
{{- range .Vars}}
# {{.Comment}}
{{.Key}}={{.Value}}
{{- end}}
{{- end}}
`

	t, err := template.New("env").Parse(tmpl)
	if err != nil {
		fmt.Printf("Error parsing template: %v\n", err)
		return
	}

	f, err := os.Create(".env")
	if err != nil {
		fmt.Printf("Error creating .env file: %v\n", err)
		return
	}
	defer f.Close()
	fmt.Println("Generating .env file...")

	if err := t.Execute(f, groups); err != nil {
		fmt.Printf("Error writing .env file: %v\n", err)
		return
	}

	fmt.Println("Successfully created .env file")
}
